1_hello_world:
	go run 1_hello-world.go
	go build 1_hello-world.go
	./1_hello-world

2_values:
	go run 2_values.go
	go build 2_values.go
	./2_values

3_variables:
	go run 3_variables.go
	go build 3_variables.go
	./3_variables

4_constants:
	go run 4_constants.go
	go build 4_constants.go
	./4_constants

5_for:
	go run 5_for.go
	go build 5_for.go
	./5_for

6_ifelse:
	go run 6_ifelse.go
	go build 6_ifelse.go
	./6_ifelse

7_switch:
	go run 7_switch.go
	go build 7_switch.go
	./7_switch

clean:
	rm -f 1_hello-world
	rm -f 2_values
	rm -f 3_variables
	rm -f 4_constants
	rm -f 5_for
	rm -f 6_ifelse
	rm -f 7_switch