FROM ubuntu:16.04
MAINTAINER Carlos Llano <carlos_llano@hotmail.com>

################################################################################
# Install requirements: git, jq, python
################################################################################
RUN apt-get update
RUN apt-get -y install vim git jq curl sudo wget rsyslog tee
RUN apt-get -y install python python-pip 
RUN pip install --upgrade pip

# Install rabbitmq
RUN echo 'deb http://www.rabbitmq.com/debian/ testing main' | tee /etc/apt/sources.list.d/rabbitmq.list
RUN wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -
RUN apt-get update
RUN apt-get install rabbitmq-server -y

# Configure rabbitmq
RUN rabbitmq-plugins enable rabbitmq_management
RUN rabbitmqctl add_user admin password
RUN rabbitmqctl set_user_tags admin administrator
RUN rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
RUN rabbitmqctl delete_user guest
RUN service rabbitmq-server restart