version: "3"
services:
  rabbitmq_server:
      image: rabbitmq:3.8.10-management-alpine
      container_name: rabbitmq_server
      environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      ports:
          - 5672:5672
          - 15672:15672
  rabbitmq_client:
      build: './rabbitmq_client'
      links: 
          - rabbitmq_server
      networks:
          - default
      volumes:
        - "./:/home/workdir"
      tty: true