# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: universidad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'universidad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11universidad.proto\"%\n\x0cIdEstudiante\x12\x15\n\rid_estudiante\x18\x01 \x01(\x05\"Z\n\x0eInfoEstudiante\x12\x15\n\rid_estudiante\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rrera\x18\x03 \x01(\t\x12\x10\n\x08semestre\x18\x04 \x01(\x05\"D\n\x0fNuevoEstudiante\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61rrera\x18\x02 \x01(\t\x12\x10\n\x08semestre\x18\x03 \x01(\x05\"H\n\x11RespuestaRegistro\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x13\n\x0bid_asignado\x18\x03 \x01(\x05\x32\x8c\x01\n\x14SistemaUniversitario\x12\x35\n\x11ObtenerEstudiante\x12\r.IdEstudiante\x1a\x0f.InfoEstudiante\"\x00\x12=\n\x13RegistrarEstudiante\x12\x10.NuevoEstudiante\x1a\x12.RespuestaRegistro\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'universidad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDESTUDIANTE']._serialized_start=21
  _globals['_IDESTUDIANTE']._serialized_end=58
  _globals['_INFOESTUDIANTE']._serialized_start=60
  _globals['_INFOESTUDIANTE']._serialized_end=150
  _globals['_NUEVOESTUDIANTE']._serialized_start=152
  _globals['_NUEVOESTUDIANTE']._serialized_end=220
  _globals['_RESPUESTAREGISTRO']._serialized_start=222
  _globals['_RESPUESTAREGISTRO']._serialized_end=294
  _globals['_SISTEMAUNIVERSITARIO']._serialized_start=297
  _globals['_SISTEMAUNIVERSITARIO']._serialized_end=437
# @@protoc_insertion_point(module_scope)
