# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import universidad_pb2 as universidad__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in universidad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SistemaUniversitarioStub(object):
    """Sistema central de la universidad con 2 funcionalidades distintas
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerEstudiante = channel.unary_unary(
                '/SistemaUniversitario/ObtenerEstudiante',
                request_serializer=universidad__pb2.IdEstudiante.SerializeToString,
                response_deserializer=universidad__pb2.InfoEstudiante.FromString,
                _registered_method=True)
        self.RegistrarEstudiante = channel.unary_unary(
                '/SistemaUniversitario/RegistrarEstudiante',
                request_serializer=universidad__pb2.NuevoEstudiante.SerializeToString,
                response_deserializer=universidad__pb2.RespuestaRegistro.FromString,
                _registered_method=True)


class SistemaUniversitarioServicer(object):
    """Sistema central de la universidad con 2 funcionalidades distintas
    """

    def ObtenerEstudiante(self, request, context):
        """Operacion 1: Obtener detalles de un estudiante existente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarEstudiante(self, request, context):
        """Operacion 2: Registrar a un nuevo estudiante
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SistemaUniversitarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerEstudiante,
                    request_deserializer=universidad__pb2.IdEstudiante.FromString,
                    response_serializer=universidad__pb2.InfoEstudiante.SerializeToString,
            ),
            'RegistrarEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarEstudiante,
                    request_deserializer=universidad__pb2.NuevoEstudiante.FromString,
                    response_serializer=universidad__pb2.RespuestaRegistro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SistemaUniversitario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SistemaUniversitario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SistemaUniversitario(object):
    """Sistema central de la universidad con 2 funcionalidades distintas
    """

    @staticmethod
    def ObtenerEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SistemaUniversitario/ObtenerEstudiante',
            universidad__pb2.IdEstudiante.SerializeToString,
            universidad__pb2.InfoEstudiante.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SistemaUniversitario/RegistrarEstudiante',
            universidad__pb2.NuevoEstudiante.SerializeToString,
            universidad__pb2.RespuestaRegistro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
