apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials-57
  namespace: cdc-lab-file
  labels:
    stack: mysql57
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  REPL_PASSWORD: repl
  DEBEZIUM_PASSWORD: dbz
