version: '2'
services:
  spark-master:
    image: gradiant/spark:2.0.0
    ports:
      - "58080:8080"
    networks:
      - sparknet
    command: "master"

  spark-worker:
    image: gradiant/spark:2.0.0
    networks:
      - sparknet
    command: "worker"

networks:
  sparknet:
