FROM ubuntu:20.04

run apt-get  update
run apt-get install -y curl nano make vim git jq python3
run apt-get install -y build-essential
run apt-get install -y manpages-dev


# For Operating System
run apt-get  install -y gcc
run apt-get  install -y libncurses5-dev
run apt-get  install -y bison
run apt-get  install -y flex
run apt-get  install -y libssl-dev
run apt-get  install -y libelf-dev
run apt-get  upgrade -y

run apt clean && apt autoremove -y

