# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hola.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hola.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhola.proto\" \n\x0ePeticionSaludo\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"\"\n\x0fRespuestaSaludo\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2@\n\x0eServicioSaludo\x12.\n\x07Saludar\x12\x0f.PeticionSaludo\x1a\x10.RespuestaSaludo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hola_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETICIONSALUDO']._serialized_start=14
  _globals['_PETICIONSALUDO']._serialized_end=46
  _globals['_RESPUESTASALUDO']._serialized_start=48
  _globals['_RESPUESTASALUDO']._serialized_end=82
  _globals['_SERVICIOSALUDO']._serialized_start=84
  _globals['_SERVICIOSALUDO']._serialized_end=148
# @@protoc_insertion_point(module_scope)
