  # -*- mode: ruby -*-
# vim: ft=ruby


# ---- Configuration variables ----

GUI               = false # Enable/Disable GUI
RAM               = 500   # Default memory size in MB

# Network configuration
DOMAIN            = ".example.com"
NETWORK           = "192.168.56."
NETMASK           = "255.255.255.0"

# Default Virtualbox .box
# See: https://wiki.debian.org/Teams/Cloud/VagrantBaseBoxes
BOX               =  'ubuntu/xenial64' #'hashicorp/precise64' (ubuntu12.04) ubuntu/xenial64 (ubuntu16.04)

HOSTS = {
  "mysql"         => [NETWORK+"120", RAM, GUI, BOX, "mysql.sh"],
}

# ---- Vagrant configuration ----

Vagrant.configure(2) do |config|
  HOSTS.each do | (name, cfg) |
    ipaddr, ram, gui, box, provisioning_script = cfg

    config.vm.define name do |machine|
      machine.vm.box   = box
      machine.vm.guest = :ubuntu
      machine.vm.provision :shell, path: provisioning_script

      machine.vm.provider "virtualbox" do |vbox|
        vbox.gui    = gui
        vbox.memory = ram
        vbox.name = name
      end

      machine.vm.hostname = name
      machine.vm.network 'private_network', ip: ipaddr, netmask: NETMASK, name: 'vboxnet0', adapter:2
      machine.vm.network "forwarded_port", guest: 3306, host: 3306
    end


  end # HOSTS-each

end
