# -*- mode: ruby -*-
# vim: ft=ruby


# Vagrant y Virtualbox

# ---- Configuration variables ----

GUI               = false  # Enable/Disable GUI
RAM               = 2024   # Default memory size in MB
CPUS              = 1      # Default number of cpus 

# Network configuration
DOMAIN            = ".example.com"
NETWORK           = "192.168.56."
NETMASK           = "255.255.255.0"

# Default Virtualbox .box
# See: https://wiki.debian.org/Teams/Cloud/VagrantBaseBoxes
BOX               = "bento/ubuntu-20.04" # "ubuntu/bionic64" -> 18.04      "bento/ubuntu-20.04" -> 20.04

HOSTS = {
  "vagrantcontainers"   => [NETWORK+"120", RAM, GUI, BOX, CPUS, "docker.sh"]
}

# ---- Vagrant configuration ----

Vagrant.configure(2) do |config|
  HOSTS.each do | (name, cfg) |
    ipaddr, ram, gui, box, cpus, provisioning_script = cfg

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.synced_folder "./examples", "/home/vagrant/examples"

    config.vm.define name do |machine|
      machine.vm.box   = box
      machine.vm.guest = :ubuntu
      machine.vm.provision :shell, path: provisioning_script
      machine.vm.boot_timeout = 300
      machine.disksize.size = '50GB'

      machine.vm.provider "virtualbox" do |vbox|
        vbox.gui    = gui
        vbox.memory = ram
        vbox.cpus = cpus
        vbox.name = name
      end

      machine.vm.hostname = name + DOMAIN
      machine.vm.network 'private_network', ip: ipaddr, netmask: NETMASK, name: 'vboxnet0', adapter:2
    end

  end # HOSTS-each

end
